name: ospy_tests
channels:
  - conda-forge  
dependencies:
  - python=3.6
  - dask
  - distributed
  - bottleneck
  - netCDF4
  - xarray>=0.14.1
  - cartopy
  - esmpy
  - intake-xarray
  - geopy
  - xesmf
  - esmf
  - xgcm>=0.2.0
  - Ipython
  - tqdm
  - pytest
  - pytest-cov
  - pytest-env
  - codecov
  - flake8
  - ffmpeg
  - black
  - pip
  - pip:
    - git+https://github.com/MITgcm/xmitgcm.git
    - black-nb
    - pre-commit
