name: oceanspy_test
channels:
  - conda-forge  
dependencies:
  - dask
  - distributed
  - bottleneck
  - netCDF4
  - xarray>=0.14.1
  - cartopy<0.20
  - intake-xarray
  - geopy
  - xesmf!=0.5.0,!=0.5.1
  - esmf
  - xgcm>=0.2.0
  - Ipython
  - tqdm
  - pytest
  - pytest-cov
  - pytest-env
  - codecov
  - ffmpeg
  - aiohttp
  - pandas
  - matplotlib
  - fsspec!=0.9.0
  - pooch
  - xmitgcm
  - pip
