name: oceanspy_test
channels:
  - conda-forge  
dependencies:
  - dask
  - distributed
  - bottleneck
  - netCDF4
  - xarray
  - cartopy<0.20
  - intake-xarray
  - geopy
  - xesmf<0.5.0
  - esmf
  - xgcm
  - Ipython
  - tqdm
  - pytest
  - pytest-cov
  - pytest-env
  - codecov
  - ffmpeg
  - aiohttp
  - pandas
  - matplotlib
  - fsspec!=0.9.0
  - pooch
  - pip
  - pip:
    - git+https://github.com/MITgcm/xmitgcm.git
