name: rise-environment
channels:
- conda-forge
dependencies:
- python
- numpy
- matplotlib
- pandas
- bokeh
- dask
- distributed
- bottleneck
- netCDF4
- xarray
- xoak
- cartopy
- esmpy
- intake-xarray
- geopy
- xesmf > 0.6.3
- esmf
- xgcm
- Ipython
- xmitgcm
- ffmpeg
- tqdm
- pip
- pip:
  - git+https://github.com/hainegroup/oceanspy.git
  - jupyter-contrib-nbextensions
  - jupyterlab-rise
