name: rise-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - bokeh
  - rise
  - dask
  - distributed
  - bottleneck
  - netCDF4
  - xarray < 2022.6
  - cartopy
  - esmpy
  - intake-xarray
  - geopy
  - xesmf
  - esmf
  - xgcm < 0.7
  - Ipython
  - xmitgcm
  - ffmpeg
  - tqdm
  - pip
  - pip:
    - git+https://github.com/intake/intake-xarray.git
    - git+https://github.com/hainegroup/oceanspy.git
    - jupyter-contrib-nbextensions
