name: Oceanography
channels:
- conda-forge
dependencies:
- python=3.12
- dask
- numpy
- distributed
- bottleneck
- netCDF4
- xarray
- xoak
- cartopy
- esmpy
- geopy
- xesmf>0.6.3
- esmf
- xgcm
- Ipython
- tqdm
- pytest
- pytest-cov
- pytest-env
- codecov
- flake8
- ffmpeg
- black<20.8b1
- aiohttp
- pandas
- eofs
- cmocean
- gsw
- pycwt
- seaborn
- xhistogram
- nc-time-axis
- fastjmd95
- pip
- pooch
- h5netcdf
- scipy
- pydap
- zarr
- fsspec
- cftime
- rasterio
- cfgrib
- matplotlib
- cf_xarray
- ipykernel
- numba
- scikit-learn
- pys2index
- cmasher
- imageio
- pre-commit
- intake
- intake-xarray
- pip:
  - black-nb
  - numbagg
  - git+https://github.com/hainegroup/oceanspy.git
  - git+https://github.com/MITgcm/xmitgcm.git
